### ISSUE TITLE
Bad Request Invalid location addon for VPS XL at US-central 

### ISSUE THREAD

**Issue by rudyryk** [contabo/terraform-provider-contabo#12] opened 2022-11-02 22:21 UTC
Getting error while applying such configuration to create server in `US-central` region:

`API error, status code: 400, details: Bad Request Invalid location addon`

Terraform resources:

```
data "contabo_image" "ubuntu_22_04" {
  id = "afecbb85-e2fc-46f0-9684-b46b1faf00bb"
}

resource "contabo_instance" "server_003" {
  display_name = "Server-003-US-central"
  image_id = data.contabo_image.ubuntu_22_04.id
  region = "US-central"

  # Cloud Storage VPS XL SSD
  product_id = "V38"

  # Placing server at United States (Central)
  add_ons {
    id = "1322"
    quantity = 1
  }

  # Password for 'admin' user (check Secrets API)
  root_password = 111111

  # SSH keys for 'admin' user (check Secrets API)
  ssh_keys = [222222]
}
```
<img width="860" alt="Contabo-error-400-location" src="https://user-images.githubusercontent.com/4500/199613442-c0c77426-4c2a-4c46-96f6-bfd93f063372.png">

**Comment by elteir** [comment] 2022-11-11 07:50
Hi @rudyryk ,

The issue is fixed now, you can create now instances on "US-Central" with product "V38" .

**Closed** 2022-11-11 07:59 UTC
